language: go
go:
  - 1.4
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
  - gocov test -v ./... > /tmp/gocov.json
  - goveralls -gocovdata gocov.json -service travis-ci
